/*
  hub/archivebox-init.nix — Auto-provision Archivebox admin credentials.

  Companion to the `archivebox` container in `./containers.nix`. On
  first boot (or after `sudo rm /var/lib/hub/archivebox/env`) this
  oneshot generates a random ADMIN_PASSWORD into an env file that the
  container then reads via `EnvironmentFile=`.

  Pattern mirror
  --------------
  Same as `hub/vaultwarden.nix` (vaultwarden-secret-init) and
  `hub/vikunja.nix` (vikunja-secret-init): idempotent generation with
  `RemainAfterExit = false` so a deleted env file can be regenerated by
  simply restarting the podman container.

  Retrieve the generated password after first boot:
      sudo grep ADMIN_PASSWORD /var/lib/hub/archivebox/env

  Rotate the password:
      sudo rm /var/lib/hub/archivebox/env
      sudo systemctl restart podman-archivebox
*/
{ pkgs, ... }:
{
  systemd.services.archivebox-secret-init = {
    description = "Generate Archivebox ADMIN_PASSWORD on first boot";
    # Runs whenever the container is about to start. Idempotent —
    # skips if the env file already contains ADMIN_PASSWORD.
    wantedBy = [ "podman-archivebox.service" ];
    before = [ "podman-archivebox.service" ];
    path = with pkgs; [
      openssl
      coreutils
      gnugrep
    ];
    # No RemainAfterExit: we want ExecStart to run on every restart of
    # podman-archivebox so a deleted env file gets regenerated.
    serviceConfig.Type = "oneshot";
    script = ''
      set -euo pipefail
      install -d -m 0700 -o root -g root /var/lib/hub/archivebox

      if [ -s /var/lib/hub/archivebox/env ] \
         && grep -q '^ADMIN_PASSWORD=' /var/lib/hub/archivebox/env; then
        exit 0
      fi

      umask 077
      pw=$(openssl rand -base64 24)
      printf 'ADMIN_PASSWORD=%s\n' "$pw" > /var/lib/hub/archivebox/env
      chmod 0400 /var/lib/hub/archivebox/env
    '';
  };
}
