/*
  hardware/default.nix — Hardware module aggregator.

  Imports all hardware-related modules so that configuration.nix only needs
  to reference this single path (`./modules/hardware`).

  hardware-configuration.nix is auto-generated by `nixos-generate-config` and
  lives in the repository root. It must NOT be edited manually — regenerate it
  with `sudo nixos-generate-config` after hardware changes.

  The `i2c` group is declared here because it is an OS-level artefact of the
  RGB hardware subsystem (rgb.nix creates the udev rule that references it).
*/
_: {
  imports = [
    ../../hardware-configuration.nix
    ./audio.nix
    ./rgb.nix
    ./gpu-amd.nix
  ];

  # Required by rgb.nix udev rules; user "main" is added to this group
  # in modules/system/users.nix.
  users.groups.i2c = { };
}
